### ISSUE TITLE
Keyword conflict

### ISSUE THREAD

**Issue by lanceXwq** [harrisonlabollita/arXiv.jl#9]
`abs` and `all` are both functions in `Base`, passing `field=abs` or `field=all` will trigger something like

WARNING: both arXiv and Base export "abs"; uses of it in module Main must be qualified
ERROR: UndefVarError: abs not defined

Possible solutions:
1. Let users pass full words instead of acronyms, but it does not help `all`.
2. Only export the enumerated types and not the instances, then a user would have to write, for instance, `field=arXiv.abs` instead of `field=abs`.

**Comment by harrisonlabollita** [comment]
Why does this commit 1824061 not work? This is my solution to fix this, but I keep getting the error that Dict{Field, String} is not callable?

**Comment by lanceXwq** [comment]
Please see https://github.com/harrisonlabollita/arXiv.jl/commit/6624b0b624d9bf21077ac499daab27b8106f2513, it should work now

**Comment by harrisonlabollita** [comment]
So this now fixed? Should we close this down?
